language: node_js
node_js: "0.10"
secure: "NDDRc3eclg/sc3sc6bJq7WX0VuSQeQTg8OwgyCXHi5Cg9wyLLXe3ajzx4glLvsqq8uIl+dRE5HpJ5lEyrTMdxWHspUrVbfjRp4JuujoMbdsLjMzOeZZxuYHMGLbJnCWvN0lxNcosiXKydLEaOxgD79sCEJF549TtiHPMXeTl2z8="
env:
  - ES_BRANCH=master COVERAGE=1
  - ES_BRANCH=1.0 NODE_UNIT=0
  - ES_BRANCH=0.90 NODE_UNIT=0
  - NODE_UNIT=0 NODE_INTEGRATION=0 BROWSER_UNIT=1
script: ./scripts/ci.sh
email:
  recipients:
    - spencer.alger@elasticsearch.com
  on_success: change
  on_failure: always