---
name: ðŸ‘® Security Issue
description: Responsible disclosure
body:
  - type: markdown
    attributes:
      value: |
        If you want to report a security issue, please take a look at [elastic/security](https://github.com/elastic/.github/blob/main/SECURITY.md).
